//
//  HomeContainerPresenter.swift
//  SpiralPay
//
//  Created by Zoeb on 09/03/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeContainerPresentationLogic
{
    func getPaymentDetailSuccessWith(response: Home.PaymentDetail.Response)
    func getPaymentDetailFailureWith(response: Home.PaymentDetail.Response)
}

class HomeContainerPresenter: HomeContainerPresentationLogic
{
  weak var viewController: HomeContainerDisplayLogic?
    
    func getPaymentDetailSuccessWith(response: Home.PaymentDetail.Response) {
        viewController?.getPaymentDetailSuccessWith(response: response)
    }
    
    func getPaymentDetailFailureWith(response: Home.PaymentDetail.Response) {
        viewController?.getPaymentDetailFailureWith(response: response)
    }
    
}
