//
//  HomeContainerWorker.swift
//  SpiralPay
//
//  Created by Zoeb on 09/03/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias getCampaignsResponseHandler = (_ response:Home.GetCampaigns.Response) ->()

class HomeContainerWorker
{
    
    func getPaymentDetailWith(request: Home.PaymentDetail.Request, successCompletionHandler: @escaping paymentDetailResponseHandler, failureCompletionHandler: @escaping paymentDetailResponseHandler)
    {
        RequestManager().getPaymentDetail(request: request.baseRequest()) { (status, response) in
            self.handleGetPaymentDetailResponse(success: successCompletionHandler, fail: failureCompletionHandler, status: status, response: response)
        }
    }
    
    func getCampaignsWith(request: Home.GetCampaigns.Request, successCompletionHandler: @escaping getCampaignsResponseHandler, failureCompletionHandler: @escaping getCampaignsResponseHandler)
    {
        RequestManager().getCampaigns(request: request.baseRequest()) { (status, response) in
            self.handleGetCampaignsResponse(success: successCompletionHandler, fail: failureCompletionHandler, status: status, response: response)
        }
    }
    
    //MARK: Parse methods
    
    public func handleGetPaymentDetailResponse(success:@escaping(paymentDetailResponseHandler), fail:@escaping(paymentDetailResponseHandler), status: Bool, response: Any?) {
        var message:String = Constants.kErrorMessage
        if status {
            if let result = response as? Home.PaymentDetail.Response {
                success(result)
                return
            }
        }
        else {
            if let result = response as? Home.PaymentDetail.Response {
                fail(result)
                return
            }
            else
            {
                if let result = response as? String {
                    message = result
                }
            }
        }
        fail(Home.PaymentDetail.Response(message:message)!)
    }
    
    public func handleGetCampaignsResponse(success:@escaping(getCampaignsResponseHandler), fail:@escaping(getCampaignsResponseHandler), status: Bool, response: Any?) {
        var message:String = Constants.kErrorMessage
        if status {
            if let result = response as? Home.GetCampaigns.Response {
                success(result)
                return
            }
        }
        else {
            if let result = response as? Home.GetCampaigns.Response {
                fail(result)
                return
            }
            else
            {
                if let result = response as? String {
                    message = result
                }
            }
        }
        fail(Home.GetCampaigns.Response(message:message)!)
    }
    
}
