//
//  DollarOneCardVerificationInteractor.swift
//  SpiralPay
//
//  Created by Zoeb on 04/06/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DollarOneCardVerificationBusinessLogic
{
    func dollarOneCardVerification(request: DollarOneCardVerification.DollarOneCardVerification.Request)
}

protocol DollarOneCardVerificationDataStore
{
    
}

class DollarOneCardVerificationInteractor: DollarOneCardVerificationBusinessLogic, DollarOneCardVerificationDataStore
{
    var presenter: DollarOneCardVerificationPresentationLogic?
    var worker: DollarOneCardVerificationWorker?
    
    func dollarOneCardVerification(request: DollarOneCardVerification.DollarOneCardVerification.Request) {
        worker = DollarOneCardVerificationWorker()
        worker?.dollarOneCardVerification(request: request, successCompletionHandler: { (response) in
            self.presenter?.dollarOneCardVerificationAPIsuccess(response: response)
        }, failureCompletionHandler: { (response) in
            self.presenter?.dollarOneCardVerificationAPIfailure(response: response)
        })
    }
}
