//
//  DollarOneCardVerificationWorker.swift
//  SpiralPay
//
//  Created by Zoeb on 04/06/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias dollarOneCardVerificationResponseHandler = (_ response:DollarOneCardVerification.DollarOneCardVerification.Response) ->()

class DollarOneCardVerificationWorker
{
    
    func dollarOneCardVerification(request: DollarOneCardVerification.DollarOneCardVerification.Request, successCompletionHandler: @escaping dollarOneCardVerificationResponseHandler, failureCompletionHandler: @escaping dollarOneCardVerificationResponseHandler)
    {
        RequestManager().dollarOneCardVerification(request: request.baseRequest()) { (status, response) in
            self.handleDollarOneCardVerificationResponse(success: successCompletionHandler, fail: failureCompletionHandler, status: status, response: response)
        }
        
    }
    
    //MARK: Parse methods
    
    public func handleDollarOneCardVerificationResponse(success:@escaping(dollarOneCardVerificationResponseHandler), fail:@escaping(dollarOneCardVerificationResponseHandler), status: Bool, response: Any?) {
        let message:String = Constants.kErrorMessage
        if status {
            success(DollarOneCardVerification.DollarOneCardVerification.Response(message: "Dollar one card verification succeded")!)
            return
        }
        fail(DollarOneCardVerification.DollarOneCardVerification.Response(message:message)!)
    }
}
