//
//  ChangePinModels.swift
//  SpiralPay
//
//  Created by Zoeb on 02/04/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ObjectMapper

let changePinSuffix = "/change_pin"

enum ChangePin
{
    // MARK: Use cases
    
    enum ChangePin
    {
        struct Request
        {
            private var deviceID:String! = "did_\(UserDefaults.standard.value(forKey: Constants.deviceIdentifier)!)"
            var currentPin: String?
            var newPin: String?
            
            func baseRequest() -> BaseRequest {
                let baseRequest = BaseRequest()
                baseRequest.urlPath = "/v1/wallet/customers/\(User.shared.customerID ?? "-")\(changePinSuffix)"
                baseRequest.parameters["device_id"] = deviceID
                baseRequest.parameters["current_pin_code"] = currentPin ?? ""
                baseRequest.parameters["new_pin_code"] = newPin ?? ""
                return baseRequest
            }
        }
        
        struct Response: Mappable {
            
            private struct SerializationKeys {
                static let error = "error"
                static let message = "message"
            }
            
            public var error: String?
            public var message: String?
            
            public init?(map: Map){
                
            }
            public init?(message: String){
                self.message = message
            }
            
            public mutating func mapping(map: Map) {
                error <- map[SerializationKeys.error]
                message <- map[SerializationKeys.message]
            }
            
            public func dictionaryRepresentation() -> [String: Any] {
                var dictionary: [String: Any] = [:]
                if let value = error { dictionary[SerializationKeys.error] = value }
                if let value = message { dictionary[SerializationKeys.message] = value }
                return dictionary
            }
            
        }
    }
}
