//
//  ChangePinRouter.swift
//  SpiralPay
//
//  Created by Zoeb on 02/04/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ChangePinRoutingLogic
{
    func routeToEnterNewPinScreenWith(currentPin: String)
}

protocol ChangePinDataPassing
{
    var dataStore: ChangePinDataStore? { get }
}

class ChangePinRouter: NSObject, ChangePinRoutingLogic, ChangePinDataPassing
{
    weak var viewController: ChangePinViewController?
    var dataStore: ChangePinDataStore?
    
    func routeToEnterNewPinScreenWith(currentPin: String) {
        
        let enterNewPinViewController: ChangePinViewController = ChangePinViewController.create()
        enterNewPinViewController.changePinEntry = .New
        enterNewPinViewController.currentPin = currentPin
        
        viewController?.navigationController?.pushViewController(enterNewPinViewController, animated: true)
    }
}
