//
//  ChangePinWorker.swift
//  SpiralPay
//
//  Created by Zoeb on 02/04/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias changePinResponseHandler = (_ response: ChangePin.ChangePin.Response) ->()

class ChangePinWorker
{
    func postCustomerRegistrationWith(request: ChangePin.ChangePin.Request, successCompletionHandler: @escaping changePinResponseHandler, failureCompletionHandler: @escaping changePinResponseHandler)
    {
        RequestManager().changePin(request: request.baseRequest()) { (status, response) in
            self.handleChangePinResponse(success: successCompletionHandler, fail: failureCompletionHandler, status: status, response: response)
        }
        
    }
    
    //MARK: Parse methods
    
    public func handleChangePinResponse(success:@escaping(changePinResponseHandler), fail:@escaping(changePinResponseHandler), status: Bool, response: Any?) {
        let message:String = Constants.kErrorMessage
        if status {
            success(ChangePin.ChangePin.Response(message: "Pin changed successfully")!)
            return
        }
        fail(ChangePin.ChangePin.Response(message:message)!)
    }
}
