//
//  ChangePinPresenter.swift
//  SpiralPay
//
//  Created by Zoeb on 02/04/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangePinPresentationLogic
{
    func changePinSuccess(response: ChangePin.ChangePin.Response)
    func changePinFailed(response: ChangePin.ChangePin.Response)
}

class ChangePinPresenter: ChangePinPresentationLogic
{
    weak var viewController: ChangePinDisplayLogic?
    
    func changePinSuccess(response: ChangePin.ChangePin.Response) {
        viewController?.changePinSuccess(response: response)
    }
    
    func changePinFailed(response: ChangePin.ChangePin.Response) {
        viewController?.changePinFailed(response: response)
    }
}
