//
//  LockAccountPresenter.swift
//  SpiralPay
//
//  Created by Zoeb on 06/04/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LockAccountPresentationLogic
{
    func lockAccountSuccess(response: LockAccount.LockAccount.Response)
    func lockAccountFailed(response: LockAccount.LockAccount.Response)
}

class LockAccountPresenter: LockAccountPresentationLogic
{
    weak var viewController: LockAccountDisplayLogic?
    
    func lockAccountSuccess(response: LockAccount.LockAccount.Response) {
        viewController?.lockAccountSuccess(response: response)
    }
    
    func lockAccountFailed(response: LockAccount.LockAccount.Response) {
        viewController?.lockAccountFailed(response: response)
    }
    
}
