//
//  LockAccountRouter.swift
//  SpiralPay
//
//  Created by Zoeb on 06/04/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LockAccountRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol LockAccountDataPassing
{
    var dataStore: LockAccountDataStore? { get }
}

class LockAccountRouter: NSObject, LockAccountRoutingLogic, LockAccountDataPassing
{
    weak var viewController: LockAccountViewController?
    var dataStore: LockAccountDataStore?
    
    
}
