//
//  ChangeEmailViewController.swift
//  SpiralPay
//
//  Created by Zoeb on 03/04/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangeEmailDisplayLogic: class
{
    func updateMobileAndEmailSuccess(response: PhoneVerification.UpdateMobileAndEmail.Response)
    func updateMobileAndEmailFailure(response: PhoneVerification.UpdateMobileAndEmail.Response)
}

class ChangeEmailViewController: SpiralPayViewController, ChangeEmailDisplayLogic
{
    var interactor: ChangeEmailBusinessLogic?
    var router: (NSObjectProtocol & ChangeEmailRoutingLogic & ChangeEmailDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = ChangeEmailInteractor()
        let presenter = ChangeEmailPresenter()
        let router = ChangeEmailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    @IBOutlet weak var emailAddressTextField: FloatingHeaderTextField!
    @IBOutlet weak var saveButton: SpiralPayButton!
    @IBOutlet weak var errorLabel: UILabel!
    
    //MARK:- APIs
    
    //MARK: Update email
    
    func updateMobileAndEmailSuccess(response: PhoneVerification.UpdateMobileAndEmail.Response) {
        NLoader.stopAnimating()
        User.shared.save()
        self.navigationController?.popToRootViewController(animated: true)
    }
    
    func updateMobileAndEmailFailure(response: PhoneVerification.UpdateMobileAndEmail.Response) {
        NLoader.stopAnimating()
        errorLabel.isHidden = false
    }
    
    //MARK:- IBAction methods
    
    @IBAction func backButtonTapped() {
        self.navigationController?.popViewController(animated: true)
    }
    
    @IBAction func saveButtonTapped() {
        User.shared.email = emailAddressTextField.text
        
        NLoader.startAnimating()
        interactor?.updateMobileAndEmail(request: PhoneVerification.UpdateMobileAndEmail.Request())
    }
    
    //MARK:- Private methods
    
    func checkIfEntriesValid() -> Bool {
        var message = ""
        
        if !emailAddressTextField.isValidEmail() {
            message = "Please enter a valid email address."
        }
        
        saveButton.isSelected = message.isEmpty
        return !message.isEmpty
    }
    
}

extension ChangeEmailViewController: UITextFieldDelegate {
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
    
    func textFieldDidBeginEditing(_ textField: UITextField) {
        saveButton.isSelected = false
        errorLabel.isHidden = true
    }
    
    func textFieldDidEndEditing(_ textField: UITextField) {
        _ = self.checkIfEntriesValid()
    }
    
}
