//
//  ChangeEmailInteractor.swift
//  SpiralPay
//
//  Created by Zoeb on 03/04/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangeEmailBusinessLogic
{
    func updateMobileAndEmail(request: PhoneVerification.UpdateMobileAndEmail.Request)
}

protocol ChangeEmailDataStore
{

}

class ChangeEmailInteractor: ChangeEmailBusinessLogic, ChangeEmailDataStore
{
    var presenter: ChangeEmailPresentationLogic?
    var worker: ChangeEmailWorker?
    
    func updateMobileAndEmail(request: PhoneVerification.UpdateMobileAndEmail.Request) {
        PhoneVerificationWorker().updateMobileAndEmail(request: request, successCompletionHandler: { (response) in
            self.presenter?.updateMobileAndEmailAPIsuccess(response: response)
        }, failureCompletionHandler: { (response) in
            self.presenter?.updateMobileAndEmailAPIfailure(response: response)
        })
    }
}
