//
//  PinPresenter.swift
//  SpiralPay
//
//  Created by Zoeb on 02/02/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PinPresentationLogic
{
  func presentSomething(response: Pin.Something.Response)
}

class PinPresenter: PinPresentationLogic
{
  weak var viewController: PinDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Pin.Something.Response)
  {
    let viewModel = Pin.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
