//
//  PinPresenter.swift
//  SpiralPay
//
//  Created by Zoeb on 02/02/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PinPresentationLogic
{
    func customerRegistrationSuccess(response: Pin.CustomerRegistration.Response)
    func customerRegistrationFailed(response: Pin.CustomerRegistration.Response)
    
    func loginSuccess(response: Pin.Login.Response)
    func loginFailed(response: Pin.Login.Response)
}

class PinPresenter: PinPresentationLogic
{
    weak var viewController: PinDisplayLogic?
    
    //MARK: Customer registration
    
    func customerRegistrationSuccess(response: Pin.CustomerRegistration.Response)
    {
        viewController?.customerRegistrationSuccess(response: response)
    }
    
    func customerRegistrationFailed(response: Pin.CustomerRegistration.Response) {
        viewController?.customerRegistrationFailed(response: response)
    }
    
    //MARK: Login
    
    func loginSuccess(response: Pin.Login.Response)
    {
        viewController?.loginSuccess(response: response)
    }
    
    func loginFailed(response: Pin.Login.Response) {
        viewController?.loginFailed(response: response)
    }
    
}
