//
//  PinRouter.swift
//  SpiralPay
//
//  Created by Zoeb on 02/02/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PinRoutingLogic
{
    func routeToReEnterPinScreenWith(pin: String)
}

protocol PinDataPassing
{
  var dataStore: PinDataStore? { get }
}

class PinRouter: NSObject, PinRoutingLogic, PinDataPassing {
    
  weak var viewController: PinViewController?
  var dataStore: PinDataStore?
    
    var createdPin: String!
  
  // MARK: Routing

    func routeToReEnterPinScreenWith(pin: String) {
        createdPin = pin
        
        let reEnterPinViewController: PinViewController = PinViewController.create(of: .Main)
        passDataTo(source: viewController!, destination: reEnterPinViewController)
        navigateTo(source: viewController!, destination: reEnterPinViewController)
    }

    // MARK: Navigation
  
  func navigateTo(source: PinViewController, destination: UIViewController)
  {
    source.show(destination, sender: nil)
  }
  
//   MARK: Passing data
  
  func passDataTo(source: PinViewController, destination: UIViewController)
  {
    if let reEnterPinViewController = destination as? PinViewController {
        reEnterPinViewController.pinEntry = .ReEnter
        reEnterPinViewController.createdPin = createdPin
    }
  }
}
