//
//  PinViewController.swift
//  SpiralPay
//
//  Created by Zoeb on 02/02/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PinEntry {
    case Create
    case ReEnter
    case Login
}

protocol PinDisplayLogic: class
{
    func customerRegistrationSuccess(response: Pin.CustomerRegistration.Response)
    func customerRegistrationFailed(response: Pin.CustomerRegistration.Response)
    
    func loginSuccess(response: Pin.Login.Response)
    func loginFailed(response: Pin.Login.Response)
}

class PinViewController: ProgressBarViewController, PinDisplayLogic
{
  var interactor: PinBusinessLogic?
  var router: (NSObjectProtocol & PinRoutingLogic & PinDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = PinInteractor()
    let presenter = PinPresenter()
    let router = PinRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        initialSetup()
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        self.navigationController?.setNavigationBarHidden(true, animated: false)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        codeTextField.becomeFirstResponder()
    }
  
  // MARK: Do something
    
    @IBOutlet weak var codeTextField: UITextField!
    @IBOutlet weak var headingLabel: UILabel!
    @IBOutlet weak var passwordDoesntMatch: UILabel!
    @IBOutlet var pins: [UIButton]!
    
    var pinEntry: PinEntry = .Create
    var createdPin: String?
    
    var screenType = AppFlowType.Onboard
    
    let pinDoesntMatchText = "PIN code doesn't match"
    
    //MARK: - API
    //MARK: Customer registration
    func doCustomerRegistrationWith(pin: String?)
    {
        NLoader.startAnimating()
        
        //This removes space from country code
        
        var request = Pin.CustomerRegistration.Request()
        request.email = User.shared.email
        request.pinCode = pin
        request.phone = User.shared.phoneWithCode
        interactor?.doCustomerRegistration(request: request)
    }
    
    func customerRegistrationSuccess(response: Pin.CustomerRegistration.Response) {
        NLoader.stopAnimating()
        
        User.shared.accessToken = response.accessToken
        User.shared.customerID = response.customerId
        if screenType == .Onboard {
            User.shared.savedState = SavedState.PinCreated
        }
        User.shared.save()
        
        Utils.shared.startAccessTokenExpiryTimer()
        
        router?.routeToPhoneVerificationProcess()
    }
    
    func customerRegistrationFailed(response: Pin.CustomerRegistration.Response) {
        NLoader.stopAnimating()
    }
    
    //MARK: Login
    
    func loginSuccess(response: Pin.Login.Response) {
        
        Utils.shared.startAccessTokenExpiryTimer()
        
        NLoader.shared.stopNLoader()
        
        User.shared.accessToken = response.accessToken
//        User.shared.accessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpudWxsLCJ1c2VyX25hbWUiOiJkaWRfMDc5MTlDRTktMUU1RC00MTZELTgzRTYtREY0MTQzNzcyNkZGIiwic2NvcGUiOlsicXJfcGF5bWVudF9jcmVhdGUiLCJxcl9wYXltZW50X3ZpZXciLCJtZXJjaGFudF92aWV3IiwicXJfcGF5bWVudF9wcm9jZXNzIiwiY3VzdG9tZXJfbWFuYWdlIiwicGF5bWVudF92aWV3Il0sIm1lcmNoYW50X2lkIjpudWxsLCJleHAiOjE1MjAyNTY4NDEsImN1c3RvbWVyX2lkIjoiNGRkODI5MDItNzNhNi00MzZiLTk4ZjQtMTk0MTMyOTdhODk1IiwiYXV0aG9yaXRpZXMiOlsibWVyY2hhbnRfdmlldyIsInFyX3BheW1lbnRfY3JlYXRlIiwicXJfcGF5bWVudF92aWV3IiwicGF5bWVudF92aWV3IiwicXJfcGF5bWVudF9wcm9jZXNzIiwiY3VzdG9tZXJfbWFuYWdlIl0sImp0aSI6IjRjOGI1MmQwLWVkMDgtNGFmMC04ODc0LWEyMzcyMWQ4ZTFlOCIsImNsaWVudF9pZCI6InByb21ldGhldXMiLCJ1c2VybmFtZSI6ImRpZF8wNzkxOUNFOS0xRTVELTQxNkQtODNFNi1ERjQxNDM3NzI2RkYifQ.b-I08eqY_EFYCU7clItw7whLcEAonq-_PHgBRlWsfAQ"
        User.shared.save()

        if self == ApplicationDelegate.getWindow().rootViewController { //If its the very first screen of app
            ApplicationDelegate.openIntendedScreen()
//            ApplicationDelegate.showHomeTabBarScreen()
        } else {
            self.dismiss(animated: true, completion: {
                ApplicationDelegate.executeUniversalLinkingBlock()
            })
        }
        
        DispatchQueue.global().async {
            Utils.shared.startGetVerificationResultTimer(shouldCallApiAtStartOnce: true)
        }
    }
    
    func loginFailed(response: Pin.Login.Response) {
        NLoader.shared.stopNLoader()
        
        if response.errorDescription != nil {
            passwordDoesntMatch.text = response.errorDescription
        }
        
        self.passwordDoesntMatch.isHidden = false

        selectDotWith(count: 0)
        codeTextField.text = ""
        codeTextField.becomeFirstResponder()
    }
    
    //MARK:- Private methods
    
    private func initialSetup() {
        if pinEntry == .Create {
            percentageOfProgressBar = CGFloat(2/numberOfProgressBarPages)
        } else if pinEntry == .ReEnter {
            percentageOfProgressBar = CGFloat(3/numberOfProgressBarPages)
        } else {
            progressBar.isHidden = true
        }
        
        if pinEntry == .ReEnter {
            headingLabel.text = "Re-enter PIN Code"
        } else if pinEntry == .Login {
            headingLabel.text = "Enter PIN Code"
            passwordDoesntMatch.text = pinDoesntMatchText
            Utils.shared.stopAccessTokenExpiryTimer()
        }
    }
    
    private func selectDotWith(count: Int) {
        var pinCount = 1
        for pin in pins {
            pin.isSelected = pinCount <= count
            pinCount = pinCount + 1
        }
    }
    
    private func pinCreationAndMatchingDoneLocally() {
        doCustomerRegistrationWith(pin: codeTextField.text)
    }
    
    private func doLoginCheckWith(pin: String?) {
        passwordDoesntMatch.isHidden = true
        
        //Reset old access token
        User.shared.accessToken = nil
        
        NLoader.shared.startNLoader()
        
        var request = Pin.Login.Request()
        request.pinCode = pin

        self.interactor?.doLogin(request: request)
    }
    
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        if !codeTextField.isFirstResponder {
            codeTextField.becomeFirstResponder()
        }
    }
}

extension PinViewController: UITextFieldDelegate {
    
    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        let updatedText = textField.text!.replacingCharacters(in: Range(range, in: textField.text ?? "")!, with: string)
        
        selectDotWith(count: updatedText.count)
        
        passwordDoesntMatch.isHidden = true
        passwordDoesntMatch.text = pinDoesntMatchText
        
        if updatedText.count <= 5 {
            
            if updatedText.count == 5 {
                if pinEntry == .Create {
                    router?.routeToReEnterPinScreenWith(pin: updatedText)
                } else if pinEntry == .ReEnter {
                    if createdPin != updatedText {
                        passwordDoesntMatch.isHidden = false
                    } else {
                        textField.text = updatedText
                        codeTextField.resignFirstResponder()
                        
                        pinCreationAndMatchingDoneLocally()
                    }
                } else {
                    textField.text = updatedText
                    codeTextField.resignFirstResponder()
                    
                    doLoginCheckWith(pin: updatedText)
                }
            }
            
            return true
        } else {
            if pinEntry == .ReEnter {
                passwordDoesntMatch.isHidden = false
            }
        }
        
        return false
    }
    
}
