//
//  ProductDetailsPresenter.swift
//  SpiralPay
//
//  Created by Zoeb on 12/03/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailsPresentationLogic
{
    func processPaymentSuccessWith(response: ProductDetails.ProcessPayment.Response)
    func processPaymentFailureWith(response: ProductDetails.ProcessPayment.Response)
    
    func getCardTokenSuccessWith(response: ProductDetails.CardToken.Response)
    func getCardTokenFailureWith(response: ProductDetails.CardToken.Response)
}

class ProductDetailsPresenter: ProductDetailsPresentationLogic
{
    weak var viewController: ProductDetailsDisplayLogic?
    
    func processPaymentSuccessWith(response: ProductDetails.ProcessPayment.Response) {
        viewController?.processPaymentSuccessWith(response: response)
    }
    
    func processPaymentFailureWith(response: ProductDetails.ProcessPayment.Response) {
        viewController?.processPaymentFailureWith(response: response)
    }
    
    func getCardTokenSuccessWith(response: ProductDetails.CardToken.Response) {
        viewController?.getCardTokenSuccessWith(response: response)
    }
    
    func getCardTokenFailureWith(response: ProductDetails.CardToken.Response) {
        viewController?.getCardTokenFailureWith(response: response)
    }
    
}
