//
//  HomePresenter.swift
//  SpiralPay
//
//  Created by Zoeb on 22/02/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func getPaymentHistorySuccessWith(response: [Home.PaymentHistory.Response])
    func getPaymentHistoryFailureWith(response: Home.PaymentHistory.Response)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    func getPaymentHistorySuccessWith(response: [Home.PaymentHistory.Response]) {
        viewController?.getPaymentHistorySuccessWith(response: response)
    }
    
    func getPaymentHistoryFailureWith(response: Home.PaymentHistory.Response) {
        viewController?.getPaymentHistoryFailureWith(response: response)
    }
    
}
