//
//  CountryPresenter.swift
//  SpiralPay
//
//  Created by Zoeb on 31/01/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryPresentationLogic
{
  func presentSomething(response: Country.Something.Response)
}

class CountryPresenter: CountryPresentationLogic
{
  weak var viewController: CountryDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Country.Something.Response)
  {
    let viewModel = Country.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
