//
//  CountryRouter.swift
//  SpiralPay
//
//  Created by Zoeb on 31/01/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CountryRoutingLogic
{
  func saveCountryWithCodeAndDismiss()
}

protocol CountryDataPassing
{
  var dataStore: CountryDataStore? { get }
}

class CountryRouter: NSObject, CountryRoutingLogic, CountryDataPassing
{
  weak var viewController: CountryViewController?
  var dataStore: CountryDataStore?
  
  // MARK: Routing
    
    func saveCountryWithCodeAndDismiss() {
        if viewController?.selectedCellIndex != -1 {
            let countryName: String = viewController!.filteredCountries[viewController!.selectedCellIndex]
            let countryPhoneCode: String = viewController!.countriesAndPhoneCodes[countryName] ?? ""
            
            viewController?.countrySelectionDelegate?.performActionWith(countryName: countryName, countryPhoneCode: countryPhoneCode)
        }
        viewController?.navigationController?.popViewController(animated: true)
    }
    
}
