//
//  CountryInteractor.swift
//  SpiralPay
//
//  Created by Zoeb on 31/01/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CountryBusinessLogic
{
  func doSomething(request: Country.Something.Request)
}

protocol CountryDataStore
{
  //var name: String { get set }
}

class CountryInteractor: CountryBusinessLogic, CountryDataStore
{
  var presenter: CountryPresentationLogic?
  var worker: CountryWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Country.Something.Request)
  {
    worker = CountryWorker()
    worker?.doSomeWork()
    
    let response = Country.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
