//
//  PhoneAndEmailInteractor.swift
//  SpiralPay
//
//  Created by Zoeb on 29/01/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneAndEmailBusinessLogic
{
  func doSomething(request: PhoneAndEmail.Something.Request)
}

protocol PhoneAndEmailDataStore
{
  //var name: String { get set }
}

class PhoneAndEmailInteractor: PhoneAndEmailBusinessLogic, PhoneAndEmailDataStore
{
  var presenter: PhoneAndEmailPresentationLogic?
  var worker: PhoneAndEmailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PhoneAndEmail.Something.Request)
  {
    worker = PhoneAndEmailWorker()
    worker?.doSomeWork()
    
    let response = PhoneAndEmail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
