
//  PhoneAndEmailViewController.swift
//  SpiralPay
//
//  Created by Zoeb on 29/01/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AppFlowType {
    case Onboard
    case Setting
}

protocol PhoneAndEmailDisplayLogic: class
{
  func displaySomething(viewModel: PhoneAndEmail.Something.ViewModel)
}

class PhoneAndEmailViewController: ProgressBarViewController, PhoneAndEmailDisplayLogic
{
  var interactor: PhoneAndEmailBusinessLogic?
  var router: (NSObjectProtocol & PhoneAndEmailRoutingLogic & PhoneAndEmailDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = PhoneAndEmailInteractor()
    let presenter = PhoneAndEmailPresenter()
    let router = PhoneAndEmailRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    percentageOfProgressBar = CGFloat(1/numberOfProgressBarPages)
    super.viewDidLoad()
    initialSetup()

    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        self.navigationController?.setNavigationBarHidden(true, animated: false)
    }
  
  // MARK: Do something
    
    @IBOutlet weak var countryCodeLabel: UILabel!
    @IBOutlet weak var countryCodeTextField: FloatingHeaderTextField!
    @IBOutlet weak var mobileNumberTextField: FloatingHeaderTextField!
    @IBOutlet weak var emailAddressTextField: FloatingHeaderTextField!
    @IBOutlet weak var nextButton: SpiralPayButton!
    
    var countryName: String?
    var countryPhoneCode: String?
    
    var screenType = AppFlowType.Onboard
  
  func doSomething()
  {
    let request = PhoneAndEmail.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: PhoneAndEmail.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
    
    //MARK:- IBAction methods
    
    @IBAction func nextButtonTapped(button: UIButton) {
        if screenType == .Onboard {
            User.shared.countryName = countryName
            User.shared.countryPhoneCode = countryPhoneCode
            User.shared.phone = mobileNumberTextField.text
            User.shared.email = emailAddressTextField.text
            router?.routeToCreatePin()
        } else {
            User.shared.countryName = countryName
            User.shared.countryPhoneCode = countryPhoneCode
            User.shared.phone = mobileNumberTextField.text
            
            let phoneVerificationViewController: PhoneVerificationViewController = PhoneVerificationViewController.create()
            phoneVerificationViewController.screenType = .Setting
            self.navigationController?.pushViewController(phoneVerificationViewController, animated: true)
        }
    }
    
    @IBAction func countryButtonTapped(button: UIButton) {
        router?.routeToCountrySelection()
    }
    
    @IBAction func backButtonTapped() {
        self.navigationController?.popViewController(animated: true)
    }
    
    //MARK:- Private methods
    
    func initialSetup() {
        self.navigationController?.setNavigationBarHidden(true, animated: false)
        let dropDownArrowImage = UIImage(named: "dropDownArrow")
        let dropDownArrowImageView = UIImageView(frame: CGRect(x: 0, y: 0, width: 20, height: 30))
        dropDownArrowImageView.image = dropDownArrowImage
        dropDownArrowImageView.contentMode = .center
        countryCodeTextField.rightView = dropDownArrowImageView
        countryCodeTextField.rightViewMode = .always
        
        countryName = "United Kingdom"
        countryPhoneCode = "44"
        if screenType == .Setting {
            countryName = User.shared.countryName
            countryPhoneCode = User.shared.countryPhoneCode
            
            if let countryPhoneCode = countryPhoneCode {
                countryCodeLabel.text = "+\(countryPhoneCode)"
            }
            mobileNumberTextField.text = User.shared.phone
        }
    }
    
    func checkIfEntriesValid() -> Bool {
        var message = ""
        
        if screenType == .Onboard {
            if !emailAddressTextField.isValidEmail() {
                message = "Please enter a valid email address."
            }
        }
        if !mobileNumberTextField.isValidPhoneNumber() {
            message = "Please enter a valid mobile number."
        }
        
        nextButton.isSelected = message.isEmpty
        return !message.isEmpty
    }
    
}

extension PhoneAndEmailViewController: UITextFieldDelegate {
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
    
    func textFieldDidBeginEditing(_ textField: UITextField) {
        nextButton.isSelected = false
    }
    
    func textFieldDidEndEditing(_ textField: UITextField) {
        _ = self.checkIfEntriesValid()
    }
    
    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        
        if textField == mobileNumberTextField {
            let currentText = textField.text ?? ""
            guard let stringRange = Range(range, in: currentText) else { return false }
            
            let updatedText = currentText.replacingCharacters(in: stringRange, with: string)
            
            let charSet = CharacterSet(charactersIn: "1234567890").inverted
            
            if updatedText.rangeOfCharacter(from: charSet) != nil || updatedText.count > 10 {
                return false
            }
        }
        
        return true
        
    }
}

extension PhoneAndEmailViewController: CountrySelectionDelegate {
    
    func performActionWith(countryName: String, countryPhoneCode: String) {
        self.countryName = countryName
        self.countryPhoneCode = countryPhoneCode
        
        countryCodeLabel.text = "+\(countryPhoneCode)"
    }
    
}
