//
//  PhoneAndEmailPresenter.swift
//  SpiralPay
//
//  Created by Zoeb on 29/01/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PhoneAndEmailPresentationLogic
{
  func presentSomething(response: PhoneAndEmail.Something.Response)
}

class PhoneAndEmailPresenter: PhoneAndEmailPresentationLogic
{
  weak var viewController: PhoneAndEmailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PhoneAndEmail.Something.Response)
  {
    let viewModel = PhoneAndEmail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
