//
//  PhoneAndEmailRouter.swift
//  SpiralPay
//
//  Created by Zoeb on 29/01/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PhoneAndEmailRoutingLogic
{
    func routeToCountrySelection()
}

protocol PhoneAndEmailDataPassing
{
  var dataStore: PhoneAndEmailDataStore? { get }
}

class PhoneAndEmailRouter: NSObject, PhoneAndEmailRoutingLogic, PhoneAndEmailDataPassing
{
  weak var viewController: PhoneAndEmailViewController?
  var dataStore: PhoneAndEmailDataStore?
  
  // MARK: Routing
    
    func routeToCountrySelection() {
        let countryViewController: CountryViewController = viewController?.storyboard?.instantiateViewController(withIdentifier: "CountryViewController") as! CountryViewController
        countryViewController.countrySelectionDelegate = viewController
        countryViewController.defaultCountryName = User.shared.countryName
        
        navigateToSomewhere(source: viewController!, destination: countryViewController)
    }

   //MARK: Navigation
  
  func navigateToSomewhere(source: PhoneAndEmailViewController, destination: CountryViewController)
  {
    source.show(destination, sender: nil)
  }
  
   //MARK: Passing data
  
  func passDataToSomewhere(source: PhoneAndEmailDataStore, destination: inout CountryViewController)
  {

  }
}
