//
//  PhoneAndEmailWorker.swift
//  SpiralPay
//
//  Created by Zoeb on 29/01/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PhoneAndEmailWorker
{
  func doSomeWork()
  {
  }
}
