//
//  ConfirmDetailsInteractor.swift
//  SpiralPay
//
//  Created by Zoeb on 09/02/18.
//  Copyright (c) 2018 EnvisionWorld. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfirmDetailsBusinessLogic
{
  func doSomething(request: ConfirmDetails.Something.Request)
}

protocol ConfirmDetailsDataStore
{
  //var name: String { get set }
}

class ConfirmDetailsInteractor: ConfirmDetailsBusinessLogic, ConfirmDetailsDataStore
{
  var presenter: ConfirmDetailsPresentationLogic?
  var worker: ConfirmDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ConfirmDetails.Something.Request)
  {
    worker = ConfirmDetailsWorker()
    worker?.doSomeWork()
    
    let response = ConfirmDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
