import Foundation
public class documentRecord{
     public var amount : String = ""
     public var comments : String = ""
     public var countryOfIssue : String = ""
     public var dateOfBirthMatchesForm : String = ""
     public var documentExpiryDate : String = ""
     public var documentName : String = ""
     public var documentNumber : String = ""
     public var filler : String = ""
     public var id : Int64 = 0
     public var idDocumentType : String = ""
     public var idWizardRefNo : String = ""
     public var issuedBy : String = ""
     public var issuedate : String = ""
     public var nameMatchesform : String = ""
     public var photoMatch : String = ""
     public var recordNo : String = ""
     public var recordType : String = ""
     public var referenceNo : String = ""
     public var residentialAddressMatchesForm : String = ""
     public var stateOrTerritoryOfIssue : String = ""
     public var utilityAccountIssuer : String = ""
     public var utilityAccountType : String = ""
}
